on:
  push:
    branches:
      - edge
      - topic/alr_ci
    tags:
      - 2*.*.*
  workflow_dispatch:

name: Build binaries
env:
  DEFAULT_TAG: 24.0.999
jobs:
  build:
    name: Build and deploy
    strategy:
      fail-fast: false
      matrix: # Build debug and/or production
        os: [macos-12, macos-14, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Initialize TAG and git autocrlf
        shell: bash
        run: |
          git config --global core.autocrlf input
          if [[ ${GITHUB_REF##*/} = 2*.[0-9]*.[0-9]* ]]; then
              echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          else
              echo "TAG=$DEFAULT_TAG" >> $GITHUB_ENV
          fi
      - name: Get als
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Alire
        if: ${{ matrix.os == 'macos-14' }}
        run: |
          curl -L -O https://github.com/alire-project/alire/releases/download/nightly/alr-nightly-bin-aarch64-macos.zip
          unzip alr-nightly-bin-aarch64-macos.zip
          bin/alr index --reset-community
          bin/alr toolchain --select gnat_native^14 gprbuild^24
          echo $PWD/bin >> $GITHUB_PATH
      - name: Get GNAT toolchain with alire
        if: ${{ matrix.os != 'macos-14' }}
        uses: alire-project/setup-alire@v3
        with:
          toolchain: gnat_native^14 gprbuild^24
      - name: Build
        run: |
          alr settings --global --set dependencies.shared false
          scripts/build_als.sh all "$TAG"
      - name: Archive ALS binary
        uses: actions/upload-artifact@v4
        with:
          name: als-${{ matrix.os }}
          # We know that only one of the following entries will match on a given
          # run, so we use globs here to try to avoid warnings on unmatched
          # entries
          path: |
            integration/vscode/ada/arm*
            integration/vscode/ada/x64*
      - name: Package
        run: |
          .github/workflows/pack-binaries.sh "$TAG"
      - name: Archive ALS binary
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v4
        with:
          name: vsix-${{ matrix.os }}
          # We know that only one of the following entries will match on a given
          # run, so we use globs here to try to avoid warnings on unmatched
          # entries
          path: |
            *.vsix
