on:
  push:
    branches:
      - edge
    tags:
      - 2*.*.*
name: Build binaries
env:
  DEFAULT_TAG: 24.0.999
  AWS_DEFAULT_REGION: eu-west-1
jobs:
  build:
    name: Build and deploy
    strategy:
      fail-fast: false
      matrix: # Build debug and/or production
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Initialize TAG and git autocrlf
        shell: bash
        run: |
          git config --global core.autocrlf input
          if [[ ${GITHUB_REF##*/} = 2*.[0-9]*.[0-9]* ]]; then
              echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
          else
              echo "TAG=$DEFAULT_TAG" >> $GITHUB_ENV
          fi
      - name: Get als
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get GNAT toolchain with alire
        uses: alire-project/setup-alire@v3
        # TBD Get alr nightly build to have it on MacOS X!!!
        with:
          version: "nightly"
#          toolchain: gnat_native^14 gprbuild^22
      - name: Build
        run: |
          scripts/build_als.sh all ${{ env.TAG }}
      - name: Archive ALS binary
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v3
        with:
          name: als-${{ matrix.os }}
          # We know that only one of the following entries will match on a given
          # run, so we use globs here to try to avoid warnings on unmatched
          # entries
          path: |
            integration/vscode/ada/arm*
            integration/vscode/ada/x64*
  package:
    if: false
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get als
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Pack vscode extension
        run: |
          if [[ ${GITHUB_REF##*/} = 2*.[0-9]*.[0-9]* ]]; then
              TAG="${GITHUB_REF##*/}"
              .github/workflows/release.sh ""      "${{ secrets.GITHUB_TOKEN }}" $TAG
              # .github/workflows/release.sh "debug" "${{ secrets.GITHUB_TOKEN }}" $TAG
          else
              TAG="$DEFAULT_TAG"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          .github/workflows/pack-binaries.sh ""      "${{secrets.VSCE_TOKEN}}" "${{secrets.OPENVSX_TOKEN}}" $TAG
          # .github/workflows/pack-binaries.sh "debug" "${{secrets.VSCE_TOKEN}}" "${{secrets.OPENVSX_TOKEN}}" $TAG
      - name: Archive ALS vsix
        uses: actions/upload-artifact@v3
        with:
          name: als-vsix-${{ matrix.debug }}${{ env.TAG }}
          path: '*.vsix'
